#!/usr/bin/env bash

set -eou pipefail

function usage() {
  cat <<USAGE
usage: $0 [FILE]

Parses an haproxy log FILE, or standard input, and groups requests by source.

With no FILE, or when FILE is -, read standard input.

USAGE
  exit;
}

while getopts ":h" arg; do
  case ${arg} in
    h)
      usage
      ;;
    \?)
      echo "Invalid option: -${OPTARG}" >&2
      exit 1;
      ;;
  esac
done

shift $((OPTIND-1))

[[ $# -gt 1 ]] && usage

INPUT=${1:-/dev/stdin}

awk '{gsub(":", " ", $6); print $6}' ${INPUT} \
  | awk -F. '{printf "%s.%s.%s\n", $1, $2, $3}' \
  | sort | uniq -c | sort -k1,1 -rn
